version: 2.1
jobs:
    build_and_test:
        docker:
            - image: circleci/node:lts
            
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}-v1
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-v1
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}-v1
           
            - run:
                  name: Testing
                  command: yarn run test -- --collectCoverage --watchAll=false
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: junit
            - store_test_results:
                  path: junit
            - store_artifacts:
                  path: junit
workflows:
    default:
        jobs:
            - build_and_test